import type {
  AdminUser,
  AuditLogEntry,
  CatalogProduct,
  Category,
  SupplierProduct,
  SyncRun,
} from "./types";

export const demoCategories: Category[] = [
  {
    id: "cat-brindes",
    name: "Brindes corporativos",
    slug: "brindes-corporativos",
    sortOrder: 10,
    isActive: true,
  },
  {
    id: "cat-identificacao",
    name: "Identificacao",
    slug: "identificacao",
    sortOrder: 20,
    isActive: true,
  },
  {
    id: "cat-personalizados",
    name: "Personalizados",
    slug: "personalizados",
    sortOrder: 30,
    isActive: true,
  },
  {
    id: "cat-pecas-tecnicas",
    name: "Pecas tecnicas",
    slug: "pecas-tecnicas",
    sortOrder: 40,
    isActive: true,
  },
];

export const demoSupplierProducts: SupplierProduct[] = [
  {
    id: "sup-prod-001",
    supplierId: "supplier-asia-import",
    supplierName: "Asia Import",
    externalId: "AI-CUP-500-BLK",
    rawName: "Copo termico 500ml preto",
    rawCategory: "Drinkware",
    rawImageUrls: ["/images/gallery/copo-termico-gravado.webp"],
    cost: { currency: "BRL", amountInCents: 3890 },
    suggestedPrice: { currency: "BRL", amountInCents: 7490 },
    stockAvailable: 34,
    lastImportedAt: "2026-07-28T12:30:00.000Z",
    importStatus: "mapped",
  },
  {
    id: "sup-prod-002",
    supplierId: "supplier-asia-import",
    supplierName: "Asia Import",
    externalId: "AI-NFC-TAG-01",
    rawName: "Tag NFC branca",
    rawCategory: "NFC",
    rawImageUrls: ["/images/gallery/cartao-metal-nfc.webp"],
    cost: { currency: "BRL", amountInCents: 1490 },
    suggestedPrice: { currency: "BRL", amountInCents: 3290 },
    stockAvailable: 58,
    lastImportedAt: "2026-07-25T09:00:00.000Z",
    importStatus: "pending_review",
  },
];

export const demoCatalogProducts: CatalogProduct[] = [
  {
    id: "catalog-001",
    sku: "SCX-001",
    title: "Copo termico gravado",
    categoryId: "cat-brindes",
    supplierProductId: "sup-prod-001",
    publicationStatus: "published",
    price: { currency: "BRL", amountInCents: 7490 },
    cost: { currency: "BRL", amountInCents: 3890 },
    stock: { policy: "tracked", quantity: 34, lowStockThreshold: 10 },
    images: [
      {
        id: "img-001",
        productId: "catalog-001",
        url: "/images/gallery/copo-termico-gravado.webp",
        altText: "Copo termico gravado",
        source: "curated",
        sortOrder: 1,
      },
    ],
    tags: ["brinde", "laser uv", "copo"],
    updatedAt: "2026-07-28",
  },
  {
    id: "catalog-002",
    sku: "SCX-002",
    title: "Plaqueta metalica com QR Code",
    categoryId: "cat-identificacao",
    publicationStatus: "published",
    price: { currency: "BRL", amountInCents: 1890 },
    cost: { currency: "BRL", amountInCents: 820 },
    stock: { policy: "tracked", quantity: 120, lowStockThreshold: 25 },
    images: [],
    tags: ["qr code", "plaqueta", "identificacao"],
    updatedAt: "2026-07-26",
  },
  {
    id: "catalog-003",
    sku: "SCX-003",
    title: "Tag NFC personalizada",
    categoryId: "cat-identificacao",
    supplierProductId: "sup-prod-002",
    publicationStatus: "hidden",
    price: { currency: "BRL", amountInCents: 3290 },
    cost: { currency: "BRL", amountInCents: 1490 },
    stock: { policy: "tracked", quantity: 58, lowStockThreshold: 12 },
    images: [],
    tags: ["nfc", "tag", "identificacao"],
    updatedAt: "2026-07-25",
  },
  {
    id: "catalog-004",
    sku: "SCX-004",
    title: "Caneta corporativa gravada",
    categoryId: "cat-brindes",
    publicationStatus: "published",
    price: { currency: "BRL", amountInCents: 1290 },
    cost: { currency: "BRL", amountInCents: 520 },
    stock: { policy: "tracked", quantity: 240, lowStockThreshold: 50 },
    images: [],
    tags: ["caneta", "brinde"],
    updatedAt: "2026-07-22",
  },
  {
    id: "catalog-005",
    sku: "SCX-005",
    title: "Placa em acrilico para presente",
    categoryId: "cat-personalizados",
    publicationStatus: "hidden",
    price: { currency: "BRL", amountInCents: 5590 },
    cost: { currency: "BRL", amountInCents: 2100 },
    stock: { policy: "made_to_order", quantity: 16 },
    images: [],
    tags: ["acrilico", "presente"],
    updatedAt: "2026-07-20",
  },
  {
    id: "catalog-006",
    sku: "SCX-006",
    title: "Componente tecnico em aluminio",
    categoryId: "cat-pecas-tecnicas",
    publicationStatus: "published",
    price: { currency: "BRL", amountInCents: 8990 },
    cost: { currency: "BRL", amountInCents: 4300 },
    stock: { policy: "tracked", quantity: 9, lowStockThreshold: 5 },
    images: [],
    tags: ["aluminio", "peca tecnica"],
    updatedAt: "2026-07-18",
  },
];

export const demoUsers: AdminUser[] = [
  {
    id: "user-owner",
    name: "Proprietario SCX",
    email: "owner@example.local",
    role: "owner",
    isActive: true,
  },
  {
    id: "user-manager",
    name: "Gestor de catalogo",
    email: "manager@example.local",
    role: "manager",
    isActive: true,
  },
  {
    id: "user-seller",
    name: "Vendedor",
    email: "seller@example.local",
    role: "seller",
    isActive: true,
  },
];

export const demoSyncRuns: SyncRun[] = [
  {
    id: "sync-20260728-001",
    source: "supplier_import",
    status: "completed",
    startedAt: "2026-07-28T12:30:00.000Z",
    finishedAt: "2026-07-28T12:31:20.000Z",
    importedCount: 2,
    mappedCount: 1,
  },
];

export const demoAuditLog: AuditLogEntry[] = [
  {
    id: "audit-001",
    actorUserId: "user-manager",
    action: "sync_run_completed",
    entityType: "sync_run",
    entityId: "sync-20260728-001",
    occurredAt: "2026-07-28T12:31:20.000Z",
    summary: "Importacao demonstrativa de fornecedor finalizada.",
  },
  {
    id: "audit-002",
    actorUserId: "user-manager",
    action: "publication_status_changed",
    entityType: "catalog_product",
    entityId: "catalog-003",
    occurredAt: "2026-07-25T10:10:00.000Z",
    summary: "Produto mantido oculto para revisao de preco e imagem.",
  },
];
